/* 
--------------------------------------------------------------------------------
						CONSULTAS DE PRUEBA
--------------------------------------------------------------------------------
*/

SELECT * FROM USER_PLAYER
SELECT * FROM LEAGUE
SELECT * FROM RACE
SELECT * FROM TEAM
SELECT * FROM DRIVER
SELECT * FROM USER_TEAM
SELECT * FROM USER_CLASSIFICATION
SELECT * FROM RESULT_RACE
--SELECT * FROM POINTS_DRIVER
--SELECT * FROM POINTS_TEAM
GO

DELETE FROM RESULT_RACE WHERE ID_RESULT_RACE = 3
SELECT * FROM RESULT_RACE
GO

/* ----------------------- PROCEDURES ----------------------- */


/*________________RACE________________*/

-- MUESTRA LOS DATOS DE TODOS LOS CIRCUITOS
CREATE PROCEDURE SP_GET_RACE
AS
	SELECT * FROM RACE
GO
	
-- MUESTRA LOS DATOS DE UN SOLO CIRCUITO
CREATE PROCEDURE SP_FIND_RACE (@ID INT)
AS
	SELECT * FROM RACE
	WHERE ID_RACE = @ID
GO

-- CREA UN NUEVO REGISTRO DE CARRERA
CREATE PROCEDURE SP_CREATE_RACE 
(@GPNAME NVARCHAR(100), @CIRCUITNAME NVARCHAR(100), @COUNTRY NVARCHAR(100), @GPDATESTART NVARCHAR(50), @GPDATEEND NVARCHAR(50), 
@GPLENGTH INT, @GPDISTANCE DECIMAL(6,3), @TURN INT, @LAP INT, @LASTWINNER NVARCHAR(50), @FASTLAP NVARCHAR(100))
AS
	INSERT INTO RACE 
	VALUES(@GPNAME, @CIRCUITNAME, @COUNTRY, @GPDATESTART, @GPDATEEND, @GPLENGTH, @GPDISTANCE, @TURN, @LAP, @LASTWINNER, @FASTLAP);
GO

-- ACTUALIZA UN REGISTRO DE CARRERA
CREATE PROCEDURE SP_UPDATE_RACE 
(@IDRACE INT, @GPNAME NVARCHAR(100), @CIRCUITNAME NVARCHAR(100), @COUNTRY NVARCHAR(100), @GPDATESTART NVARCHAR(50), @GPDATEEND NVARCHAR(50), 
@GPLENGTH INT, @GPDISTANCE DECIMAL(6,3), @TURN INT, @LAP INT, @LASTWINNER NVARCHAR(50), @FASTLAP NVARCHAR(100))
AS
	UPDATE RACE SET GP_NAME = @GPNAME, CIRCUIT_NAME = @CIRCUITNAME, COUNTRY = @COUNTRY, GP_DATE_START = @GPDATESTART,
	GP_DATE_END = @GPDATEEND, GP_LENGTH = @GPLENGTH,GP_DISTANCE = @GPDISTANCE, TURN = @TURN, LAP = @LAP, LAST_WINNER = @LASTWINNER, 
	FAST_LAP = @FASTLAP 
	WHERE ID_RACE = @IDRACE
GO



/*________________SCHEDULE________________*/

-- MUESTRA TODOS LOS DATOS DEL SCHEDULE
CREATE PROCEDURE SP_GET_SCHEDULE
AS
	SELECT * FROM SCHEDULE
GO


/*________________USER_PLAYER________________*/

-- OBTENCION DE UN USUARIO
CREATE PROCEDURE SP_GET_USERPLAYER
AS
	SELECT * FROM USER_PLAYER
GO

-- FILTRO POR EMAIL PARA EL REGISTRO DE UN NUEVO USUARIO
CREATE PROCEDURE SP_FIND_USERPLAYER_EMAIL (@EMAIL NVARCHAR(100))
AS
	SELECT USER_EMAIL FROM USER_PLAYER WHERE USER_EMAIL = @EMAIL
GO

-- CREACION DE UN USUARIO
CREATE PROCEDURE SP_CREATE_USERPLAYER
(@ID INT, @NICKNAME NVARCHAR(50), @EMAIL NVARCHAR(100), @PASSWORD NVARCHAR(100), @PASSWORD_SHA VARBINARY(100), @SALT NVARCHAR(100))
AS
	INSERT INTO USER_PLAYER VALUES(@ID, @NICKNAME, @EMAIL, @PASSWORD, @PASSWORD_SHA, @SALT)
GO



/*________________TEAM________________*/

-- MUESTRA LOS DATOS DE TODOS LOS EQUIPOS
CREATE PROCEDURE SP_GET_TEAM
AS
	SELECT * FROM TEAM
GO
	
-- MUESTRA LOS DATOS DE UN SOLO EQUIPO
CREATE PROCEDURE SP_FIND_TEAM (@ID INT)
AS
	SELECT * FROM TEAM
	WHERE ID_TEAM = @ID
GO



/*________________DRIVER________________*/

-- MUESTRA LOS DATOS DE TODOS LOS PILOTOS
CREATE PROCEDURE SP_GET_DRIVER
AS
	SELECT * FROM DRIVER
GO
	
-- MUESTRA LOS DATOS DE UN SOLO PILOTO
CREATE PROCEDURE SP_FIND_DRIVER (@ID INT)
AS
	SELECT * FROM DRIVER
	WHERE ID_DRIVER = @ID
GO

-- BUSCADOR DEL DRIVER POR NOMBRE
CREATE PROCEDURE SP_FIND_DRIVER_NAME (@NAMEDRIVER NVARCHAR(100))
AS
	SELECT * FROM DRIVER
	WHERE DRIVER_NAME = @NAMEDRIVER
GO



/*________________USER TEAM________________*/             /*________________CREAR VISTA________________*/

CREATE OR ALTER VIEW V_USERTEAM
AS
	SELECT 
	CAST(ROW_NUMBER() OVER (ORDER BY ID_USER) AS INT) AS POSICION,
	UT.ID_USER, UT.ID_USER_TEAM, UT.USER_TEAM_NAME AS USER_TEAM_NAME, UT.TEAM_MONEY AS BUDGET, 
	D.DRIVER_NAME,	D.PRICE AS DRIVER_PRICE, D.DRIVER_IMG,
	T.TEAM_NAME AS TEAM, T.PRICE AS TEAM_PRICE, T.TEAM_IMG
	FROM USER_TEAM UT
	INNER JOIN DRIVER_USER_TEAM DUT ON UT.ID_USER_TEAM = DUT.ID_USER_TEAM 
	INNER JOIN DRIVER D ON DUT.ID_DRIVER = D.ID_DRIVER
	INNER JOIN TEAM T ON UT.ID_TEAM = T.ID_TEAM
	--WHERE UT.ID_USER_TEAM = 2
GO


-- MUESTRA LOS DATOS DE TODOS LOS EQUIPOS DEL USUARIO
CREATE PROCEDURE SP_GET_USERTEAM (@ID INT)
AS
	SELECT * FROM V_USERTEAM
	WHERE ID_USER = 2
GO

-- MUESTRA LOS DATOS DE UN SOLO EQUIPO DEL USUARIO
CREATE PROCEDURE SP_FIND_USERTEAM (@IDUSER INT, @IDTEAM INT)
AS
	SELECT * FROM V_USERTEAM
	WHERE ID_USER = @IDUSER AND ID_USER_TEAM = @IDTEAM
GO

-- CREA UN EQUIPO NUEVO AL USUARIO, PARA ELLO HAY QUE CREAR PRIMERO EL EQUIPO CON LA ESCUDERIA Y DESPUES SE AÑADEN LOS PILOTOS
CREATE PROCEDURE SP_CREATE_USERTEAM (@TEAMNAME NVARCHAR(30), @IDUSER INT, @IDTEAM INT)
AS
	INSERT INTO USER_TEAM VALUES(@TEAMNAME,100.0,@IDUSER,@IDTEAM);
GO

CREATE PROCEDURE SP_INSERT_DRIVER_USERTEAM (@IDMAX INT, @IDUSERTEAM INT, @IDDRIVER INT)
AS
	INSERT INTO DRIVER_USER_TEAM VALUES(@IDMAX, @IDUSERTEAM, @IDDRIVER);
GO

-- ACTUALIZAR PILOTOS EN EL EQUIPO
CREATE PROCEDURE SP_UPDATE_DRIVER_USERTEAM (@IDDRIVER INT, @IDDRIVERTEAM INT)
AS
	UPDATE DRIVER_USER_TEAM SET ID_DRIVER = @IDDRIVER WHERE ID_DRIVER_TEAM = @IDDRIVERTEAM
GO

-- ELIMINAR PILOTO DEL EQUIPO
CREATE PROCEDURE SP_DELETE_DRIVER_USERTEAM (@IDDRIVERTEAM INT)
AS
	DELETE FROM DRIVER_USER_TEAM WHERE ID_DRIVER_TEAM = @IDDRIVERTEAM
GO



/*________________LEAGUES________________*/

CREATE VIEW V_LEAGUE
AS
	SELECT L.ID_LEAGUE, L.LEAGUE_NAME, UP.NICKNAME, UC.USER_TOTAL_POINTS 
	FROM LEAGUE L
	INNER JOIN USER_CLASSIFICATION UC ON L.ID_LEAGUE = UC.ID_LEAGUE
	INNER JOIN USER_PLAYER UP ON UC.ID_USER = UP.ID_USER
GO

-- MUESTRA TODAS LAS LIGAS
CREATE PROCEDURE SP_GET_LEAGUE
AS
	SELECT * FROM LEAGUE
GO

-- MUESTRA TODAS LAS LIGAS DEL USUARIO
CREATE PROCEDURE SP_FIND_USERPLAYER_LEAGUE (@IDUSER INT)
AS
	SELECT L.LEAGUE_NAME FROM LEAGUE L
	INNER JOIN USER_CLASSIFICATION UC ON L.ID_LEAGUE = UC.ID_LEAGUE
	INNER JOIN USER_PLAYER UP ON UC.ID_USER = UP.ID_USER
	WHERE UP.ID_USER = 2
GO

-- MUESTRA LOS DATOS DE LA LIGA CON SUS PARTICIPANTES
CREATE PROCEDURE SP_GET_LEAGUE_USER (@IDLEAGUE INT)
AS
	SELECT L.ID_LEAGUE, L.LEAGUE_NAME, UP.NICKNAME, UC.USER_TOTAL_POINTS 
	FROM LEAGUE L
	INNER JOIN USER_CLASSIFICATION UC ON L.ID_LEAGUE = UC.ID_LEAGUE
	INNER JOIN USER_PLAYER UP ON UC.ID_USER = UP.ID_USER
	WHERE L.ID_LEAGUE = 1
GO

-- MUESTRA LAS LIGAS POR EL FILTRO DEL BUSCADOR POR EL NOMBRE
CREATE PROCEDURE SP_FIND_LEAGUE_NAME (@NAMELEAGUE NVARCHAR(100))
AS
	SELECT * FROM LEAGUE 
	WHERE LEAGUE_NAME LIKE + '%' + @NAMELEAGUE + '%'
GO

-- BUSCA UNA LIGA POR EL CODIGO PARA UNIRSE A ELLA
CREATE PROCEDURE SP_GET_LEAGUE_JOIN (@IDUSER INT, @CODLEAGUE INT)
AS
	DECLARE @IDLEAGUE INT

	SELECT @IDLEAGUE = ID_LEAGUE FROM LEAGUE WHERE LEAGUE_COD = @CODLEAGUE

	INSERT INTO USER_CLASSIFICATION VALUES(@IDUSER, 0, @IDLEAGUE);
GO

-- CREA UNA NUEVA LIGA
CREATE PROCEDURE SP_CREATE_LEAGUE (@NAMELEAGUE NVARCHAR(100), @MAXLEAGUE INT)
AS
	INSERT INTO LEAGUE VALUES(@NAMELEAGUE, @MAXLEAGUE);
GO

-- SALIR DE UNA LIGA
CREATE PROCEDURE SP_DELETE_USER_LEAGUE (@IDUSER INT, @IDLEAGUE INT)
AS
	DELETE FROM USER_CLASSIFICATION WHERE ID_USER = 2 AND ID_LEAGUE = 2
GO



/*________________RESULT RACE________________*/
CREATE OR ALTER VIEW V_RESULTRACE 
AS
	SELECT RR.POSITION_RACE, RR.LAP_TIME, D.DRIVER_NAME, T.TEAM_NAME, RR.POINTS, RR.ID_RACE
	FROM TEAM T
	INNER JOIN DRIVER D ON T.ID_TEAM = D.ID_TEAM
	INNER JOIN RESULT_RACE RR ON D.ID_DRIVER = RR.ID_DRIVER
	INNER JOIN RACE R ON RR.ID_RACE = R.ID_RACE
GO

CREATE PROCEDURE SP_CREATE_RESULTRACE (@POSITION INT, @POINTS INT, @LAPTIME NVARCHAR(100), @IDRACE INT, @IDDRIVER INT)
AS
	INSERT INTO RESULT_RACE VALUES(@POSITION, @POINTS, @LAPTIME, @IDRACE, @IDDRIVER);
GO

CREATE PROCEDURE SP_FIND_RESULTRACE (@IDRACE INT)
AS
	SELECT RR.POSITION_RACE, RR.LAP_TIME, D.DRIVER_NAME, T.TEAM_NAME, RR.POINTS, R.ID_RACE FROM TEAM T
	INNER JOIN DRIVER D ON T.ID_TEAM = D.ID_TEAM
	INNER JOIN RESULT_RACE RR ON D.ID_DRIVER = RR.ID_DRIVER
	INNER JOIN RACE R ON RR.ID_RACE = R.ID_RACE
	WHERE RR.ID_RACE = @IDRACE
	ORDER BY RR.POSITION_RACE ASC
GO

