
CREATE TABLE USER_PLAYER (
	ID_USER INT NOT NULL PRIMARY KEY, 
	NICKNAME NVARCHAR(50) NOT NULL,
	USER_EMAIL NVARCHAR(100) NOT NULL,
	USER_PASSWORD NVARCHAR(100) NOT NULL,
	USER_PASSWORD_SHA VARBINARY(MAX) NOT NULL,
	SALT NVARCHAR(100) NOT NULL
)


CREATE TABLE LEAGUE (
	ID_LEAGUE INT IDENTITY(1,1) PRIMARY KEY, 
	LEAGUE_NAME NVARCHAR(100) NOT NULL,
	LEAGUE_COD INT NOT NULL
)


CREATE TABLE TEAM (
	ID_TEAM INT IDENTITY(1,1) PRIMARY KEY, 
	TEAM_NAME NVARCHAR(100) NOT NULL,
	PRICE DECIMAL(3, 1) NOT NULL,
	TOTAL_POINTS INT NOT NULL,
	TEAM_IMG NVARCHAR(100) NOT NULL
)


CREATE TABLE RACE (
	ID_RACE INT IDENTITY(1,1) PRIMARY KEY, 
	GP_NAME NVARCHAR(100) NOT NULL,
	CIRCUIT_NAME NVARCHAR(100) NOT NULL,
	COUNTRY NVARCHAR(100) NOT NULL,
	GP_DATE_START NVARCHAR(100) NOT NULL,
	GP_DATE_END NVARCHAR(100) NOT NULL,
	GP_LENGTH INT NOT NULL,
	GP_DISTANCE DECIMAL(6, 3) NOT NULL,
	TURN INT NOT NULL,
	LAP INT NOT NULL,
	LAST_WINNER NVARCHAR(100) NOT NULL,
	FAST_LAP NVARCHAR(100) NOT NULL,
	GP_IMG NVARCHAR(100) NOT NULL
)


CREATE TABLE SCHEDULE (
	ID_SCHEDULE INT NOT NULL PRIMARY KEY, 
	SCHEDULE_NAME NVARCHAR(40) NOT NULL,
	SCHEDULE_DAY NVARCHAR(40) NOT NULL,
	SCHEDULE_TIME NVARCHAR(40) NOT NULL,
	ID_RACE INT NOT NULL,
	CONSTRAINT FK_SCHEDULE_RACE FOREIGN KEY(ID_RACE) REFERENCES RACE(ID_RACE)
)


CREATE TABLE DRIVER (
	ID_DRIVER INT PRIMARY KEY NOT NULL, 
	DRIVER_NAME NVARCHAR(100) NOT NULL,
	NACIONALITY NVARCHAR(100) NOT NULL,
	PRICE DECIMAL(3, 1) NOT NULL,
	TOTAL_POINTS INT NOT NULL,
	ID_TEAM INT NOT NULL, 
	DRIVER_IMG NVARCHAR(100) NOT NULL
	CONSTRAINT FK_DRIVER_TEAM FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM)
)


CREATE TABLE USER_TEAM (
	ID_USER_TEAM INT IDENTITY(1,1) PRIMARY KEY, 
	USER_TEAM_NAME NVARCHAR(100) NOT NULL,
	TEAM_MONEY DECIMAL(4, 1) NOT NULL,
	ID_USER INT NOT NULL,
	ID_TEAM INT NOT NULL,
	CONSTRAINT FK_USERTEAM_USERPLAYER FOREIGN KEY(ID_USER) REFERENCES USER_PLAYER(ID_USER),
	CONSTRAINT FK_USERTEAM_TEAM FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM)
)


CREATE TABLE DRIVER_USER_TEAM (
	ID_DRIVER_TEAM INT PRIMARY KEY,
	ID_USER_TEAM INT NOT NULL,
	ID_DRIVER INT NOT NULL,
	CONSTRAINT FK_DRIVERUSERTEAM_USERTEAM FOREIGN KEY(ID_USER_TEAM) REFERENCES USER_TEAM(ID_USER_TEAM),
	CONSTRAINT FK_DRIVERUSERTEAM_DRIVER FOREIGN KEY(ID_DRIVER) REFERENCES DRIVER(ID_DRIVER),
)


CREATE TABLE USER_CLASSIFICATION (
	ID_USER INT NOT NULL,
	USER_TOTAL_POINTS INT NOT NULL,
	ID_LEAGUE INT NOT NULL,
	CONSTRAINT FK_USERCLASSIFICATION_USERPLAYER FOREIGN KEY(ID_USER) REFERENCES USER_PLAYER(ID_USER),
	CONSTRAINT FK_USERCLASSIFICATION_LEAGUE FOREIGN KEY(ID_LEAGUE) REFERENCES LEAGUE(ID_LEAGUE)
)


CREATE TABLE RESULT_RACE (
	ID_RESULT_RACE INT IDENTITY(1,1) PRIMARY KEY,
	POSITION_RACE INT NOT NULL,
	POINTS INT NOT NULL,
	LAP_TIME NVARCHAR(100) NOT NULL,
	ID_RACE INT NOT NULL,
	ID_DRIVER INT NOT NULL,
	CONSTRAINT FK_RESULTRACE_RACE FOREIGN KEY(ID_RACE) REFERENCES RACE(ID_RACE),
	CONSTRAINT FK_RESULTRACE_DRIVER FOREIGN KEY(ID_DRIVER) REFERENCES DRIVER(ID_DRIVER)
)


--CREATE TABLE POINTS_DRIVER (
--	TOTAL_POINTS INT NOT NULL,
--	ID_TEAM INT NOT NULL,
--	ID_DRIVER INT NOT NULL,
--	CONSTRAINT FK_POINTSDRIVER_TEAM FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM),
--	CONSTRAINT FK_POINTSDRIVER_DRIVER FOREIGN KEY(ID_DRIVER) REFERENCES DRIVER(ID_DRIVER)
--)


--CREATE TABLE POINTS_TEAM (
--	TOTAL_POINTS INT NOT NULL,
--	ID_TEAM INT NOT NULL,
--	CONSTRAINT FK_POINTSTEAM_TEAM FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM)
--)


