use F1_2026
GO
CREATE TABLE USER_PLAYER (
    ID_USER INT IDENTITY(1,1) PRIMARY KEY,
    NICKNAME NVARCHAR(50) NOT NULL,
    USER_EMAIL NVARCHAR(100) NOT NULL UNIQUE,

    USER_PASSWORD_SHA VARBINARY(64) NOT NULL,
    SALT VARBINARY(16) NOT NULL
);

CREATE TABLE LEAGUE (
    ID_LEAGUE INT IDENTITY(1,1) PRIMARY KEY,
    LEAGUE_NAME NVARCHAR(100) NOT NULL,
    LEAGUE_COD INT NOT NULL UNIQUE
);

CREATE TABLE TEAM (
    ID_TEAM INT IDENTITY(1,1) PRIMARY KEY,
    TEAM_NAME NVARCHAR(100) NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL,
    TOTAL_POINTS INT NOT NULL DEFAULT 0,
    TEAM_IMG NVARCHAR(150) NOT NULL
);

CREATE TABLE RACE (
    ID_RACE INT IDENTITY(1,1) PRIMARY KEY,
    GP_NAME NVARCHAR(100) NOT NULL,
    CIRCUIT_NAME NVARCHAR(100) NOT NULL,
    COUNTRY NVARCHAR(100) NOT NULL,

    GP_DATE_START DATE NOT NULL,
    GP_DATE_END DATE NOT NULL,

    GP_LENGTH INT NOT NULL,
    GP_DISTANCE DECIMAL(6,3) NOT NULL,
    TURN INT NOT NULL,
    LAP INT NOT NULL,

    LAST_WINNER NVARCHAR(100) NOT NULL,
    FAST_LAP NVARCHAR(100) NOT NULL,
    GP_IMG NVARCHAR(150) NOT NULL
);

CREATE TABLE SCHEDULE (
    ID_SCHEDULE INT IDENTITY(1,1) PRIMARY KEY,
    SCHEDULE_NAME NVARCHAR(40) NOT NULL,
    SCHEDULE_DAY NVARCHAR(40) NOT NULL,
    SCHEDULE_TIME TIME NOT NULL,

    ID_RACE INT NOT NULL,
    CONSTRAINT FK_SCHEDULE_RACE 
        FOREIGN KEY(ID_RACE) REFERENCES RACE(ID_RACE)
);

CREATE TABLE DRIVER (
    ID_DRIVER INT IDENTITY(1,1) PRIMARY KEY,
    DRIVER_NAME NVARCHAR(100) NOT NULL,
    NACIONALITY NVARCHAR(100) NOT NULL,

    PRICE DECIMAL(5,2) NOT NULL,
    TOTAL_POINTS INT NOT NULL DEFAULT 0,

    ID_TEAM INT NOT NULL,
    DRIVER_IMG NVARCHAR(150) NOT NULL,

    CONSTRAINT FK_DRIVER_TEAM 
        FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM)
);

CREATE TABLE USER_TEAM (
    ID_USER_TEAM INT IDENTITY(1,1) PRIMARY KEY,
    USER_TEAM_NAME NVARCHAR(100) NOT NULL,
    TEAM_MONEY DECIMAL(6,2) NOT NULL,

    ID_USER INT NOT NULL,
    ID_TEAM INT NOT NULL,

    CONSTRAINT FK_USERTEAM_USERPLAYER 
        FOREIGN KEY(ID_USER) REFERENCES USER_PLAYER(ID_USER),

    CONSTRAINT FK_USERTEAM_TEAM 
        FOREIGN KEY(ID_TEAM) REFERENCES TEAM(ID_TEAM)
);

CREATE TABLE DRIVER_USER_TEAM (
    ID_DRIVER_TEAM INT IDENTITY(1,1) PRIMARY KEY,

    ID_USER_TEAM INT NOT NULL,
    ID_DRIVER INT NOT NULL,

    CONSTRAINT FK_DRIVERUSERTEAM_USERTEAM 
        FOREIGN KEY(ID_USER_TEAM) REFERENCES USER_TEAM(ID_USER_TEAM),

    CONSTRAINT FK_DRIVERUSERTEAM_DRIVER 
        FOREIGN KEY(ID_DRIVER) REFERENCES DRIVER(ID_DRIVER),

    CONSTRAINT UQ_DRIVER_USERTEAM UNIQUE (ID_USER_TEAM, ID_DRIVER)
);

CREATE TABLE USER_CLASSIFICATION (
    ID_USER INT NOT NULL,
    ID_LEAGUE INT NOT NULL,
    USER_TOTAL_POINTS INT NOT NULL DEFAULT 0,

    CONSTRAINT PK_USER_CLASSIFICATION 
        PRIMARY KEY (ID_USER, ID_LEAGUE),

    CONSTRAINT FK_USERCLASSIFICATION_USERPLAYER 
        FOREIGN KEY(ID_USER) REFERENCES USER_PLAYER(ID_USER),

    CONSTRAINT FK_USERCLASSIFICATION_LEAGUE 
        FOREIGN KEY(ID_LEAGUE) REFERENCES LEAGUE(ID_LEAGUE)
);

CREATE TABLE RESULT_RACE (
    ID_RESULT_RACE INT IDENTITY(1,1) PRIMARY KEY,
    POSITION_RACE INT NOT NULL,
    POINTS INT NOT NULL,
    LAP_TIME TIME NOT NULL,

    ID_RACE INT NOT NULL,
    ID_DRIVER INT NOT NULL,

    CONSTRAINT FK_RESULTRACE_RACE 
        FOREIGN KEY(ID_RACE) REFERENCES RACE(ID_RACE),

    CONSTRAINT FK_RESULTRACE_DRIVER 
        FOREIGN KEY(ID_DRIVER) REFERENCES DRIVER(ID_DRIVER)
);

GO


--VISTAS
 CREATE OR ALTER VIEW V_RESULTRACE 
AS
	SELECT RR.POSITION_RACE, RR.LAP_TIME, D.DRIVER_NAME, T.TEAM_NAME, RR.POINTS, RR.ID_RACE
	FROM TEAM T
	INNER JOIN DRIVER D ON T.ID_TEAM = D.ID_TEAM
	INNER JOIN RESULT_RACE RR ON D.ID_DRIVER = RR.ID_DRIVER
	INNER JOIN RACE R ON RR.ID_RACE = R.ID_RACE
GO

CREATE OR ALTER VIEW V_USERTEAM
AS
	SELECT 
	CAST(ROW_NUMBER() OVER (ORDER BY ID_USER) AS INT) AS POSICION,
	UT.ID_USER, UT.ID_USER_TEAM, UT.USER_TEAM_NAME AS USER_TEAM_NAME, UT.TEAM_MONEY AS BUDGET, 
	D.DRIVER_NAME,	D.PRICE AS DRIVER_PRICE, D.DRIVER_IMG,
	T.TEAM_NAME AS TEAM, T.PRICE AS TEAM_PRICE, T.TEAM_IMG
	FROM USER_TEAM UT
	INNER JOIN DRIVER_USER_TEAM DUT ON UT.ID_USER_TEAM = DUT.ID_USER_TEAM 
	INNER JOIN DRIVER D ON DUT.ID_DRIVER = D.ID_DRIVER
	INNER JOIN TEAM T ON UT.ID_TEAM = T.ID_TEAM
	--WHERE UT.ID_USER_TEAM = 2
GO

CREATE OR ALTER VIEW V_LEAGUE
AS
SELECT 
    CAST(ROW_NUMBER() OVER (ORDER BY UC.USER_TOTAL_POINTS DESC) AS INT) AS POSICION,
    UC.ID_USER,
    L.ID_LEAGUE,
    L.LEAGUE_NAME,
    UP.NICKNAME,
    UC.USER_TOTAL_POINTS 
FROM LEAGUE L
INNER JOIN USER_CLASSIFICATION UC ON L.ID_LEAGUE = UC.ID_LEAGUE
INNER JOIN USER_PLAYER UP ON UC.ID_USER = UP.ID_USER
GO

CREATE OR ALTER VIEW V_USER_CLASSIFICATION
AS
	SELECT CAST(ROW_NUMBER() OVER (ORDER BY ID_USER) AS INT) AS POSICION, ID_USER, USER_TOTAL_POINTS, ID_LEAGUE
	FROM USER_CLASSIFICATION
GO
